version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FLASK_DEBUG: "false"
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
    command: sh -c "flask db upgrade && flask run --host=0.0.0.0 --port=5000"
    restart: always
    ports:
      - "5001:5000"
    expose:
      - "5001"
    depends_on:
      - db
      - redis

  db:
    image: postgres:15.3-alpine3.18
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres_root
      - POSTGRES_PASSWORD=asdf234Kj786o
      - POSTGRES_DB=sky_db
    volumes:
      - db_postrge_sky:/var/lib/postgresql/data

  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    volumes:
      - ./data:/data
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: ["celery", "-A", "app.celery_inst", "worker", "-l", "info"]
    depends_on:
      - db
      - redis

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: ["celery", "-A", "app.celery_inst", "beat", "-l", "info"]
    depends_on:
      - db
      - redis


volumes:
  db_postrge_sky: